### ISSUE TITLE
@casl/react: Invariant Violation w/ render function

### ISSUE THREAD

**Issue by dalgleish** [stalniy/casl#109]
Ran into this while working on integration of casl with our react app.
I think it might be related to how we use babel/webpack loaders, but I'm not sure yet.

### Problem

```jsx
<Can I="view" a="Animal">
    () => <div>Fox</div>
</Can>
```

I get this error
```
Invariant Violation: React.Children.only expected to receive a single React element child.
    at invariant (/project/node_modules/fbjs/lib/invariant.js:42:15)
    at Object.onlyChild [as only] (/project/node_modules/react/cjs/react.development.js:998:31)
    at o.renderChildren (/project/node_modules/@casl/react/dist/umd/index.js:1:2864)
```

This works fine:

```jsx
<Can I="view" a="Animal">
    <div>Fox</div>
</Can>
```

Here is some boilerplate code I'm using to create the contextual `Can` component used above.

```
import { createContext } from 'react';
import { AbilityBuilder } from '@casl/ability';
import { createContextualCan } from '@casl/react';

const AbilityContext = createContext();
const Can = createContextualCan(AbilityContext.Consumer);

const ability = AbilityBuilder.define(can => {
    can('view', 'Fox');
});

export {
    AbilityContext,
    Can,
    ability
};
```

### Versions
@casl/ability@2.4.2
@casl/react@0.7.2
react@16.4.2
react-dom@16.4.2

**Comment by stalniy** [comment]
This is quite strange, I checked `createContextualCan` and it just passes children prop further. I'll investigate, thanks

**Comment by stalniy** [comment]
I think the is in my doc examples :) You should write

```jsx
<Can I="view" a="Animal">
    {() => <div>Fox</div>}
</Can>
```

Pay attention at `{  ...  }` around arrow function. I updated example. Also added support for multiple elements if `React.Fragment` is available.

Let me know if it fixes your issue

**Comment by dalgleish** [comment]
Hi sorry for the delay in my response! 
Just confirming that your suggestion worked.  Thanks for updating the documentation!
