### ISSUE TITLE
Cannot find module '@casl/ability/extra'

### ISSUE THREAD

**Issue by hckhanh** [stalniy/casl#284]
I get this error when try to upgrade to v4

```
Error: Cannot find module '@casl/ability/extra'
Require stack:
- C:\Users\hoang\WebstormProjects\back-end\utils\casl.js
- C:\Users\hoang\WebstormProjects\back-end\app.js
- C:\Users\hoang\WebstormProjects\back-end\bin\www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\hoang\WebstormProjects\back-end\utils\casl.js:2:36)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\hoang\\WebstormProjects\\back-end\\utils\\casl.js',
    'C:\\Users\\hoang\\WebstormProjects\\back-end\\app.js',
    'C:\\Users\\hoang\\WebstormProjects\\back-end\\bin\\www'
  ]
}
```

**Comment by stalniy** [comment]
Thanks for the issue, I forgot to add `extra/package.json` in resulting package :)
Fixed in 4.0.1
