### ISSUE TITLE
packRules() -- TypeError: n.map is not a function

### ISSUE THREAD

**Issue by dstampfer** [stalniy/casl#381]
**Describe the bug**
I want to populate abilities from backend to frontend (jwt payload). I planned to use packRules(), but it throws a TypeError: n.map is not a function

**To Reproduce**

```
module.exports=function defineAbilityFor(user) {
const { can, cannot, build } = new AbilityBuilder(Ability);

	switch (user.role) {
		case "admin":
			can('manage', 'all');
			break;
		
		default:
			can('read', 'POST') 
			can('delete', 'POST', { id: user.id });
			break;
	} 
	
	return build();
}
```

then:

```
const permissions = require("./permissions") // above file
var x = packRules(permissions(user))
```

Produces:
```
node.js-CASL-permissions/node_modules/@casl/ability/dist/umd/extra.js:1
!function(n,r){"object"==typeof exports&&"undefined"!=typeof module?r(exports):"function"==typeof define&&define.amd?define(["exports"],r):r(((n=n||self).casl=n.casl||{},n.casl.extra={}))}(this,(function(n){"use strict";function r(n,r,t){var e=n,u=r;if(-1!==r.indexOf(".")){var f=r.split(".");u=f.pop(),e=f.reduce((function(n,r){return n[r]=n[r]||{},n[r]}),n)}e[u]=t}var t=function(n){return n.fields};function e(n){delete this[n]}function u(n){this[n]=!0}var f=function(n){return Array.isArray(n)?n.join(","):n};n.packRules=function(n,r){return n.map((function(n){for(var t,e=[f(n.action||n.actions),"function"==typeof r?(t=n.subject,Array.isArray(t)?t:[t]).map(r).join(","):f(n.subject),n.conditions||0,n.inverted?1:0,n.fields?f(n.fields):0,n.reason||""];!e[e.length-1];)e.pop();return e}))},n.permittedFieldsOf=function(n,r,f,o){void 0===o&&(o={});var i=o.fieldsFrom||t,c=n.possibleRulesFor(r,f).filter((function(n){return n

TypeError: n.map is not a function
    at n.packRules (node.js-CASL-permissions/node_modules/@casl/ability/dist/umd/extra.js:1:549)
    at Object.<anonymous> (node.js-CASL-permissions/app.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Expected behavior**

not to throw the error // to behave as described in the api

**CASL Version**

@casl/ability@4.1.5

**Environment**:
node v12.16.1

**Comment by dstampfer** [comment]
argh, I found how to get it working after looking at this: https://github.com/stalniy/casl/issues/44

```
const serialized = packRules(permissions(user).rules)
console.log(serialized)

var frontendAbility = new Ability().update(unpackRules(serialized))
console.log(frontendAbility.can("blah", "foo"))
```

**Comment by stalniy** [comment]
Close as it works as expected. Please read the API  docs. https://casl.js.org/v4/en/api/casl-ability-extra#packrules
