### ISSUE TITLE
TypeError: t.on is not a function in next.js

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [stalniy/casl#394]
**Describe the bug**
Using `@casl/ability` + `@casl/react` in Next.js gives `TypeError: t.on is not a function` using `Can` component.

**To Reproduce**
1. Add `@casl/ability` and `@casl/react` (respective versions: `4.1.6` and `2.1.1`) to `package.json` in a new Next.js project (https://nextjs.org/docs#setup). Update dependencies using `yarn`;
2. Create a new page like this (`/pages/can-form.js`):

```
import Head from 'next/head';
import { createCanBoundTo } from '@casl/react';

import { defineSampleAbility } from '../components/define-sample-ability';

const Can = createCanBoundTo(defineSampleAbility);

export default function CanForm() {
  return (
    <>
      <Head>
        <title>Can Component works.</title>
      </Head>
      <Can I="modify" a="Member" field="given-name">
        <h1>Can Component works</h1>
      </Can>
    </>
  )
}
```

3. Create a file with some abilities like this (`/components/define-sample-ability.js`):

```
import { defineAbility } from '@casl/ability';

export function defineSampleAbility() {
  return defineAbility((can, cannot) => {
    can('modify', 'Member', ['given-name', 'family-name']);
  });
}
```

4. Run the application using `yarn run dev`.

**Expected behavior**
Screen opens and I can read "Can Component works".

**Actual Behavior**
```
t.on is not a function
TypeError: t.on is not a function
    at n.s.o (C:\Users\me\sources\nextjs-blog\node_modules\@casl\react\dist\umd\index.js:1:1256)
    at n.s.render (C:\Users\me\sources\nextjs-blog\node_modules\@casl\react\dist\umd\index.js:1:1471)
    at processChild (C:\Users\me\sources\nextjs-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3134:18)
    at resolve (C:\Users\me\sources\nextjs-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (C:\Users\me\sources\nextjs-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (C:\Users\me\sources\nextjs-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (C:\Users\me\sources\nextjs-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at render (C:\Users\me\sources\nextjs-blog\node_modules\next\dist\next-server\server\render.js:83:16)
    at Object.renderPage (C:\Users\me\sources\nextjs-blog\node_modules\next\dist\next-server\server\render.js:419:16)
    at Function.getInitialProps (C:\Users\me\sources\nextjs-blog\.next\server\static\development\pages\_document.js:293:19)
    at Object.loadGetInitialProps (C:\Users\me\sources\nextjs-blog\node_modules\next\dist\next-server\lib\utils.js:59:29)
    at Object.renderToHTML (C:\Users\me\sources\nextjs-blog\node_modules\next\dist\next-server\server\render.js:423:36)
    at async DevServer.renderToHTMLWithComponents (C:\Users\me\sources\nextjs-blog\node_modules\next\dist\next-server\server\next-server.js:652:26)
    at async DevServer.renderToHTML (C:\Users\me\sources\nextjs-blog\node_modules\next\dist\next-server\server\next-server.js:799:28)
    at async DevServer.renderToHTML (C:\Users\me\sources\nextjs-blog\node_modules\next\dist\server\next-dev-server.js:19:539)
    at async DevServer.render (C:\Users\me\sources\nextjs-blog\node_modules\next\dist\next-server\server\next-server.js:541:22)
```

**Interactive example**
https://codesandbox.io/s/pedantic-fire-5siyc?file=/.gitignore

**CASL Version**

`@casl/ability` - v = 4.1.6
`@casl/react` - v = 2.1.1

**Environment**:

Node.js v12.12.0
TypeScript (optional) v3.8.3

**Comment by stalniy** [comment]
Hi,

You incorrectly use `createCanBoundTo`. You should pass ability instance NOT a function that creates `Ability`  

Check the docs and react examples for details:
- https://casl.js.org/v4/en/package/casl-react
- https://github.com/stalniy/casl-examples#examples

**Comment by leonelsanchesdasilva** [comment]
@stalniy Thanks for the guidance. This solved my problem.

**Comment by tarvinderpc** [comment]
@stalniy  t.ability[n] is not a function I am getting this error with next Js and casl any hint on that ?

**Comment by tarvinderpc** [comment]
import { createMongoAbility } from "@casl/ability";

function updateAbility(userPermissions) {
  const rules =
    userPermissions?.map((permission) => {
      return {
        action: permission?.actions
          ?.filter((action) => Object.values(action)[0])
          .map((key) => Object.keys(key)[0]),
        subject: permission.slug,
      };
    }) || [];

  return new createMongoAbility(rules);
}
export default updateAbility;

**Comment by leonelsanchesdasilva** [comment]
@tarvinderpc In my case this was caused because my `defineSampleAbility` was a function, as I was using as an object:

```
import { defineSampleAbility } from '../components/define-sample-ability';
```

In other words, instead of using this way:

```
const Can = createCanBoundTo(defineSampleAbility);
```

I should have used this way:

```
const Can = createCanBoundTo(defineSampleAbility());
```

The problem with your code should be the same.
