### ISSUE TITLE
Checking access on ability throws an error - Prisma, Nest

### ISSUE THREAD

**Issue by the-me-0** [stalniy/casl#779]
**Describe the bug**
I've been using CASL for more than a month in a quite big project and I'm actually blocked on an error that I'm not sure comes from my side. I'm building an ability using the AbilityBuilder to whom I give my AppAbility as type, and createPrismaAbility as parameter. My middleware builds an ability this way depending on the authenticated user's roles, most of the times with conditions. As far as I could go, everything went right, but I found not long ago while creating a more complex condition being :
```typescript
can(DirectoryAction.VIEW, 'DirectoryUser', { roles: { some: { role: { unitId: CASL_ROLE.unitId } } } });
```
That conditions may provoke errors, here being an " \"equals\" does not supports comparison of arrays and objects " error. I'm certain this is caused by the condition, as changing it so a less complex object such as { roles: { some: { roleId: CASL_ROLE.id } } } works fine. In fact, every time I'm setting up a complex object after the "some" instead of a simple { key: value } pair, the error appears. For example, setting up a condition like this one :
{ roles: { some: { role: { id: CASL_ROLE.id } } } } --- won't work
{ roles: { some: { roleId: CASL_ROLE.id } } } --- will work

No typescript error detected at build, neither by studio code. I checked the types asked for the condition in the (node_modules/.prisma/client/index.d.ts) and from first to last of my object key, everything is correct and follows the allowed types for this condition (studio code should have printed me an error in any case if my condition was wrong). It's a runtime exception.
I can't make the condition easier otherwise it won't fulfill it's obligations.

See the "unitId" as an appartment ID. My goal is to give access to the authenticated user (to whom CASL_ROLE belongs) to users from the same appartment, so all users with a rome on the same "unitId".

**Error stack**
```bash
Error: "equals" does not supports comparison of arrays and objects
    at Object.validate (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@casl+prisma@1.3.3_@casl+ability@6.4.0_@prisma+client@4.9.0/node_modules/@casl/prisma/src/prisma/PrismaQueryParser.ts:24:13)
    at A.parseInstruction (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@ucast+core@1.10.2/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:111:19)
    at A.parseField (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@ucast+core@1.10.2/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:101:17)
    at A.parse (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@ucast+core@1.10.2/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:163:16)
    at A.parse (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@casl+prisma@1.3.3_@casl+ability@6.4.0_@prisma+client@4.9.0/node_modules/@casl/prisma/src/prisma/PrismaQueryParser.ts:217:18)
    at type (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@casl+prisma@1.3.3_@casl+ability@6.4.0_@prisma+client@4.9.0/node_modules/@casl/prisma/src/prisma/PrismaQueryParser.ts:144:56)
    at A.parseInstruction (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@ucast+core@1.10.2/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:115:48)
    at A.parseField (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@ucast+core@1.10.2/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:101:17)
    at A.parseFieldOperators (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@ucast+core@1.10.2/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:131:30)
    at A.parse (/home/<imagineSomething>/Documents/<SomethingElse>/<project>/node_modules/.pnpm/@ucast+core@1.10.2/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:159:33)
```

**To Reproduce**
1. Ability configuration (rules, detectSubjectType, etc)
`export type AppAbility = PureAbility<[DirectoryAction, AppSubjects], PrismaQuery>;`
Where DirectoryAction is a string enum containing actions such as VIEW, UPDATE or DELETE. 
AppSubjects definition :
```typescript
type O = {
	DirectoryRole: DirectoryRole;
        DirectoryRoleUserMapping: DirectoryRoleUserMapping;
	DirectoryUser: DirectoryUser;
	(...)
};
export type AuthSubjects = Subjects<O>; // separation of O and AuthSubjects because I have another type using O
export type AppSubjects = AuthSubjects | 'all';
```
I think all complex conditions should reproduce the behaviour. At least, the ones using "some" condition member.

**Prisma Schema**
```typescript
model DirectoryUser {
    id               BigInt   @id @default(autoincrement())
    email         String   @unique
    password  String
    roles	      DirectoryRoleUserMapping[]

    @@map("directory_users")
}

model DirectoryRoleUserMapping {
	id			BigInt				@id @default(autoincrement())
	roleId		BigInt				@map("role_id")
	role			DirectoryRole			@relation(fields: [roleId], references: [id], onDelete: Cascade, onUpdate: Cascade)
	userId		BigInt				@map("user_id")
	user			DirectoryUser			@relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)

	@@unique([roleId, userId])
	@@map("directory_role_user_mappings")
}

model DirectoryRole {
    id          		BigInt			@id @default(autoincrement())
    name        		String
    unitId			BigInt?			@map("unit_id")
    unit			BmsUnit?		@relation(fields: [unitId], references: [id], onDelete: Cascade, onUpdate: Cascade)
    rank			BigInt
    users			DirectoryRoleUserMapping[]

    @@unique([name, programId, unitId])
    @@map("directory_roles")
}
```

2. How do you check abilities
For the getMany, I check if the user has any kind of permission on the entity concerned, or I throw an error :
```typescript
if (ability.cannot(DirectoryAction.VIEW, 'DirectoryRole')) {
	throw new Error('Tried to access unauthorized resource (DirectoryRole)');
}
```
Most common typechecking in my code is this one :
```typescript
const ROLE_SUBJECT = subject('DirectoryRole', ROLE); // ROLE is the role returned by prisma
if (ability.cannot(DirectoryAction.VIEW, ROLE_SUBJECT)) {
	throw new Error('Tried to access unauthorized resource (DirectoryRole)');
}
```

**Expected behavior**
I expected more complex conditions to work, as the rest of casl implementation I have done until now.

**Interactive example** (optional, but highly desirable)
I may provide an interactive example if really needed.

**CASL Version**
`@casl/ability` - v^6.4.0
`@casl/prisma` - v^1.3.3
`prisma` - v4.9.0

**Environment**:
using `pnpm` (monorepo), nestJs, typescript, graphql and NX console among other things.
`typescript` - v~5.0.2
`ts-node` - v^10.9.1

**Comment by stalniy** [comment]
Work as expected. Please read the docs -> https://casl.js.org/v6/en/package/casl-prisma#note-on-prisma-query-runtime-interpreter

prisma doesn’t expose enough of information to produce correct types. That’s why there are edge cases that throw runtime error

**Comment by the-me-0** [comment]
Well I don't understand, is there a soluce to my problem here ? If I understand you well, it's complicated for casl lib to understand prisma types, and therefore to correctly check ability. But the doc says to use "some" operator among other things, which I already use. So is there any way I can get this to work ?

**Comment by stalniy** [comment]
Each time you go deeper into another table, you need to use operator. You go from UserRoleMapping to Role without operator. That’s why it fails. i think  `is` should work in your case

**Comment by stalniy** [comment]
```
{ roles: { some: { role: { is: { id: CASL_ROLE.id } } } } }
```
